import { EventEmitter, OnInit, TemplateRef, ElementRef, OnDestroy, Renderer } from '@angular/core';
import { TableColumnComponent } from './column.component';
import { DcEventService } from '../broadcast/broadcast.service';
export declare class TableComponent implements OnInit, OnDestroy {
    private renderer;
    private broadcast;
    template: TemplateRef<TableColumnComponent>;
    filterTemplate: any;
    tableContainer: ElementRef;
    overflowBox: ElementRef;
    headers: Array<any>;
    oddEven: any;
    isSmall: any;
    tableId: any;
    radio: boolean;
    userPersentWidth: boolean;
    hasFilter: Array<boolean>;
    _datas: any;
    datas: any;
    checkBox: boolean;
    sortEvent: EventEmitter<number>;
    checkEvent: EventEmitter<any>;
    nowSort: any;
    allSelect: boolean;
    checks: Array<boolean>;
    checks_data: any;
    currentField: any;
    scrollHeight: string;
    _parentHidden: boolean;
    curSearchValue: any;
    parentHidden: boolean;
    initWidth: any;
    resizeEvent: any;
    scrollBarWidth: any;
    showFilter: any;
    broadCastPromise: any;
    constructor(renderer: Renderer, broadcast: DcEventService);
    ngOnInit(): void;
    ngOnDestroy(): void;
    setWidth(width: any, index?: number): any;
    setDivWidth(): void;
    private initCheck();
    allSelectCheck(): void;
    checkSelect(index: number): void;
    checkOption(event: any, k: any, header: any): void;
    private sendCheckOption(header, index);
    private sendCheckEvent();
    sort(header: any): void;
    showFilterBox(event: any, header: any): void;
    hideFilter(): void;
    clickFilter(event: any, header: any, index?: any): void;
    checkEmpty(event: any, header: any, index?: number): void;
    setThCenter(isCenter: boolean): any;
    onDocumentClick($event: any): void;
}
