import { ElementRef, EventEmitter, OnInit } from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
export declare class InputComponent implements ControlValueAccessor, OnInit {
    autoFocus: boolean;
    type: string;
    disabled: boolean;
    readonly: boolean;
    dcPlaceholder: string;
    width: string;
    height: string;
    resize: string;
    maxLength: number;
    required: boolean;
    noClear: boolean;
    dcBlur: EventEmitter<any>;
    dcFocus: EventEmitter<any>;
    dcClick: EventEmitter<any>;
    dcKeyup: EventEmitter<any>;
    dcKeyenter: EventEmitter<any>;
    dcModelChange: EventEmitter<any>;
    dcInput: ElementRef;
    numtip: ElementRef;
    showValue: string;
    canNum: number;
    isNum: number;
    private onTouchedCallback;
    private onChangeCallback;
    value: string;
    constructor();
    ngOnInit(): void;
    setInputValue(val: any): void;
    setInputValid(valid?: boolean): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    writeValue(val: any): void;
    blurEvent(ev: any): void;
    focusEvent(ev: any): void;
    clickEvent(ev: any): void;
    keyupEvent(ev: any): void;
    modelChange(ev: any): void;
    keyenterEvent(ev: any): void;
    clearValue(): void;
}
