import { OnInit, EventEmitter, ComponentFactoryResolver, ElementRef } from '@angular/core';
import { Router } from '@angular/router';
export declare class NodeComponent implements OnInit {
    private resolver;
    private router;
    checkboxId: string;
    treeMoreBtn: any;
    deepIndex: number;
    parentNode: any;
    myIndex: string;
    root: boolean;
    keyId: string;
    keyName: string;
    keyChild: string;
    options: any;
    treeId: string;
    clickEvent: EventEmitter<{}>;
    extendEvent: EventEmitter<{}>;
    checkEvent: EventEmitter<{}>;
    actionBtnDom: ElementRef;
    treeNode: ElementRef;
    iconClsFolder: string;
    iconClsExpand: string;
    iconClsFile: string;
    isFirst: any;
    _nodeData: any;
    nodeData: any;
    nodeChangeEvent: EventEmitter<{}>;
    constructor(resolver: ComponentFactoryResolver, router: Router);
    init(): void;
    private needShow(node);
    ngOnInit(): void;
    initClsObj(): void;
    getFileIcon(): any;
    getFolderIcon(): any;
    getExpandIcon(): any;
    clickNode(event: any, nodeData: any): void;
    changeShow(event: any): any;
    doNodeFn(option: any): void;
    _clickNode(event: any): void;
    _extendNode(event: any): void;
    _checkNode(event: any): void;
    checkNodeEvent(event: any): void;
    shouwMoreActionBtn(ev: any): void;
    hideMe(ev: any): void;
    hideMoreBtn(ev: any): void;
    setNodeWidth(icon: any, deep: any): any;
    showActionBtn(btn: any, data: any): boolean;
}
